### ISSUE TITLE
Sign up validation (services)

### ISSUE THREAD

**Issue by LesediMoko** [COS301-SE-2023/MeetApp#253]
Please try to add conditions/restrictions when a user or organisation signs up so that the usernames are unique
I've got an idea of how services can go about it (just a suggestion):
- When a user or org creates a new account
- - call the get all users/org endpoint
- - map the results into an array of usernames 
- - use the contains method on the array of usernames and pass in the new username
- - if the check is true
- - - send a message to UI alerting that the username is take
- - if the check is false
- - - call the create user/org endpoint 

Also consider password validation on sign up if it's not already there. To ensure that the password is a certain length and other stuff

**Comment by AkaniHlungwani** [comment]
Done
