### ISSUE TITLE
build and test failed on the merge with auth-api-lesedi

### ISSUE THREAD

**Issue by Jacob-Mahloko** [COS301-SE-2023/MeetApp#86]
The backend build failed and the test failed, please double check what the issue was.

**Comment by LesediMoko** [comment]
The issue is the missing dto. It is needed by signup

**Comment by LesediMoko** [comment]
my apologies. my assumptions were incorrect. I will get to the bottom of it asap. It's more of an assertion issue. The dto is in fact there
